### ISSUE TITLE
from_query_stdio() fails on tmux send-keys

### ISSUE THREAD

**Issue by qxb3** [benjajaja/ratatui-image#87]
I'm not really sure whats going on internally or its my fault or i need to do something but:

### Repro:

Code:

```rust
use ratatui::Frame;
use ratatui_image::{picker::Picker, StatefulImage, protocol::StatefulProtocol};

struct App { image: StatefulProtocol }

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut terminal = ratatui::init();

    let picker = Picker::from_query_stdio()?;

    let dyn_img = image::ImageReader::open("./assets/Ada.png")?.decode()?;

    let image = picker.new_resize_protocol(dyn_img);

    let mut app = App { image };

    terminal.draw(|f| ui(f, &mut app))?;

    app.image.last_encoding_result().unwrap()?;

    Ok(())
}

fn ui(f: &mut Frame<'_>, app: &mut App) {
    let image = StatefulImage::default();
    f.render_stateful_widget(image, f.area(), &mut app.image);
}
```

Dependecies:

```toml
[dependencies]
crossterm = "0.28.1"
image = { version = "0.25.5", default-features = false, features = ["jpeg"] }
ratatui = "0.29.0"
ratatui-image = { version = "5.0.0", features = ["crossterm"] }
```

### Tmux

1. Open up tmux with two splits
2. In the first split send a key to run the rust code: `tmux send-keys -t 1 "cargo run" C-m`
3. You should see that it errors. Running it normally without sending keys thru tmux should just work fine.

![Image](https://github.com/user-attachments/assets/f6b9dddb-4014-40ba-84de-0eff41f92831)
